// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gylljiutocepboxjgjja.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd5bGxqaXV0b2NlcGJveGpnamphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NDYxNzgsImV4cCI6MjA2ODMyMjE3OH0.LJADkjieQU7v3wOyBMstrXi7ymwplF_ReHm5aNdcDc0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});